services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./public:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - pentest

  php:
    build:
      context: ./php
    volumes:
      - ./public:/var/www/html
    networks:
      - pentest

networks:
  pentest: {}
